<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Your_Button_List_Object</name>
   <tag></tag>
   <elementGuidId>c85f7296-f3c0-473c-8576-43b29b96dd8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@role=&quot;tablist&quot;]/li[@class=&quot;uitk-date-range-button-wrapper-natural&quot;]/button[@type=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
